---
- hosts: gluster_servers
  remote_user: root
  gather_facts: no

  tasks:
  - name: Stop kernel NFS
    service: name=nfs state=stopped

  - name: Stop network manager service
    service: name=NetworkManager state=stopped
    ignore_errors: yes

  - name: Disable network manager service
    shell: chkconfig NetworkManager off
    ignore_errors: yes

  - name: Start network service
    service: name=network state=started

  - name: Enable network service
    shell: chkconfig network on

  - name: Start pcsd service
    service: name=pcsd state=started

  - name: Enable pcsd service
    shell: chkconfig pcsd on

