---
- hosts: georep_master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Configures the geo-rep session
    georep: action=config
            mastervol="{{ mastervolname }}"
            slavevol="{{ slavevol }}"
            gluster_log_file="{{ gluster_log_file}}"
            gluster_log_level="{{ gluster_log_level }}"
            log_file="{{log_file}}"
            log_level="{{log_level}}"
            ssh_command="{{ssh_command}}"
            rsync_command="{{rsync_command}}"
            use_tarssh="{{use_tarssh}}"
            volume_id="{{volume_id}}"
            timeout="{{timeout}}"
            sync_jobs="{{sync_jobs}}"
            ignore_deletes="{{ignore_deletes}}"
            checkpoint="{{checkpoint}}"


