---
- hosts: cluster_nodes
  remote_user: root
  gather_facts: no

  tasks:
  - name: Stop kernel NFS
    service: name=nfs state=stopped

  - name: Stop network manager service
    service: name=NetworkManager state=stopped
    ignore_errors: yes

  - name: Disable network manager service
    service: name=NetworkManager enabled=no
    ignore_errors: yes

  - name: Start network service
    service: name=network state=started

  - name: Enable network service
    service: name=network enabled=yes

  - name: Start pcsd service
    service: name=pcsd state=started

  - name: Enable pcsd service
    service: name=pcsd enabled=yes

  - name: Enable pacemaker service
    service: name=pacemaker enabled=yes

  - name: GlusterFS Share Storage service
    service: name=glusterfssharedstorage enabled=yes

  - name: Enable nfs-ganesha service
    service: name=nfs-ganesha enabled=yes
