---
- hosts: gluster_servers
  remote_user: root
  gather_facts: no

  tasks:
  - name: Open/Close firewalld ports
    firewalld: port={{ item }} permanent="{{ permanent }}" state="{{ firewall_state }}"
               zone="{{ zone }}"
    with_items: "{{ ports }}"

  - name: Reloads the firewall
    shell: firewall-cmd --reload
