---
- hosts: georep_master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Generate ssh key in one of Geo-replication master nodes
    user: name="{{user}}" generate_ssh_key=yes

  - name: Copy the public key to the local
    fetch: src=~/.ssh/id_rsa.pub
           dest=/tmp/id_rsa.tmp
           flat=yes

  - name: Copying local key to slave node
    local_action: shell cat /tmp/id_rsa.tmp | ssh  "{{user}}"@{{ item }} "cat >> ~/.ssh/authorized_keys"
    with_items: "{{ groups['georep_slave'] }}"

  - name: Deleting temporal files
    local_action: file  path=/tmp/id_rsa.tmp state=absent
