---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Stops a volume
    ansible.builtin.expect:
      command: "gluster volume stop {{ volname }} force"
      responses:
        (.*)Stopping volume will make its data inaccessible(.*): "y"
#    volume:  action=stop
#             volume="{{ volname }}"
    register: result
    failed_when: "result.rc != 0 and ('already stopped' not in result.msg and 'does not exist' and 'not in the started state' not in result.msg)"
