---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
    - name: Exports/Unexports volume through NFS-Ganesha
      volume_set: action=set
                volume="{{ volname }}"
                key=ganesha.enable
                value="{{ value }}"
      when: volname is defined and volname
