---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Sets options for volume
    command: gluster volume set {{ volname }} {{ item.key }} {{ item.value }}
#    volume_set: action=set
#                volume="{{ volname }}"
#                key={{ item.key }} value={{ item.value }}
    with_items: "{{ set }}"
