---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Creates a volume
    volume:  action=create
             volume="{{ volname }}"
             bricks='{{ brick_dirs }}'
             hosts="{{ hosts }}"
             transport="{{ transport }}"
             replica="{{ replica }}"
             replica_count="{{ replica_count }}"
             arbiter_count="{{ arbiter_count }}"
             disperse="{{ disperse }}"
             disperse_count="{{ disperse_count }}"
             redundancy_count="{{ redundancy_count }}"
             force="{{ force }}"
