---
- hosts: master
  become: true
  gather_facts: no

  tasks:
  - name: Enabling quota for the volume
    quota:  action=enable
            volume="{{ volname }}"
    register: result
    failed_when: "result.rc != 0 and ('already' not in result.msg)"
