---
- hosts: master
  become: true
  gather_facts: no

  tasks:
  - name: Create the dir to mount the volume, skips if present
    file: path={{ item }} state=directory
    with_items: "{{ smb_mountpoint | default([]) }}"
    when: item is defined
    ignore_errors: yes

  - name: Pause a few seconds, allow glusterd to start before mounting
    pause: seconds=10

  - name: Mount the volumes
    mount: name={{ item }}
           src="{{ groups['master'][0]}}:{{ volname }}"
           fstype=glusterfs,
           opts=acl,
           state=mounted
    with_items: "{{ smb_mountpoint | default([]) }}"
    when: item is defined

  - name: Create Samba User if not present
    user: name="{{ smb_username }}"
    when: smb_username is defined

  - name: Provide permissions using setfacl
    command: setfacl -m user:"{{ smb_username }}":rwx "{{smb_mountpoint}}"
    when: smb_username is defined and smb_mountpoint is defined

  - name: Unmount the volumes
    mount: name="{{ item }}" src="{{ item }}" fstype=glusterfs
           state=absent
    with_items: "{{ smb_mountpoint | default([]) }}"
    when: item is defined
    ignore_errors: yes
