---
- include: vdo-create.yml
- include: pvcreate.yml
- include: vgcreate.yml
- include: lvcreate.yml
- include: fscreate.yml
- include: mount.yml
- include: tune-profile.yml
- include: glusterd-start.yml
- include: gluster-peer-probe.yml
- include: gluster-volume-create.yml
- include: gluster-volume-start.yml
- include: gluster-client-mount.yml
