---
- hosts: gluster_servers
  become: true
  gather_facts: no

  tasks:
      - name: Create VDO with specified size
        vdo:
            name="{{ item.name }}"
            state="{{ state }}"
            activated="{{ activated | default('yes') }}"
            running="{{ running | default('yes') }}"
            device="{{ item.disk | default('') }}"
            logicalsize="{{ item.logicalsize | default('') }}"
            compression="{{ compression | default('enabled') }}"
            blockmapcachesize="{{ blockmapcachesize | default('128M') }}"
            readcache="{{ readcache | default('disabled') }}"
            readcachesize="{{ readcachesize | default('0') }}"
            emulate512="{{ emulate512 | default('disabled') }}"
            slabsize="{{ slabsize | default('2G') }}"
            writepolicy="{{ writepolicy | default('auto') }}"
            indexmem="{{ indexmem | default('0.25') }}"
            indexmode="{{ indexmode | default('dense') }}"
            ackthreads="{{ ackthreads | default('1') }}"
            biothreads="{{ biothreads | default('4') }}"
            cputhreads="{{ cputhreads | default('2') }}"
            logicalthreads="{{ logicalthreads | default('1') }}"
            physicalthreads="{{ physicalthreads | default('1') }}"
        with_items: "{{ vdos | default([]) }}"
