---
- hosts: gluster_servers
  remote_user: root
  gather_facts: no       # For now do not gather facts, but would like to gather
                         # facts and use the disks from gathered facts

  tasks:
  - name: Create volume group on the disks
    vg: action="create" disks={{ item.brick }}
        vgname={{ item.vg }}
        diskcount="{{ diskcount }}"
        disktype="{{ disktype }}"
        stripesize="{{ stripesize }}"
        dalign="{{ dalign }}"
    with_items: "{{ vgnames }}"
    register: result
    failed_when: "result.rc != 0 and 'already exists' not in result.msg and 'is already in volume group' not in result.msg"
