---
# Create pv on all the disks
- name: Create Physical Volume
  pv: action={{action}} disk={{disk}}
      force={{force}}
      uuid={{uuid}}
      dataalignment={{dataalignment}}
      zero={{zero}}
      metadatasize={{metadatasize}}
  register: result
  failed_when: "result.rc != 0 and 'Physical Volume Exists' not in result.msg"

# tasks file for pvcreate
